version: '{build}'

image: Visual Studio 2019 Preview
configuration: Release

before_build:
- ps: nuget restore

build:
  verbosity: minimal

after_build:
- ps: Deploy\Prepare.ps1

artifacts:
- path: Deploy\Portable\bin\DiscordChatExporter.zip
  name: DiscordChatExporter.zip
- path: Deploy\Portable\bin\DiscordChatExporter.CLI.zip
  name: DiscordChatExporter.CLI.zip

deploy:
- provider: GitHub
  auth_token:
    secure: sjQHWRw29AMiVMn3MtidtWnAzAf1mJ+mkJ/7h1B9TIAHhkFrqwMK7LtXV+uNJ9AO
  artifact: DiscordChatExporter.zip,DiscordChatExporter.CLI.zip
  description: '[Changelog](https://github.com/Tyrrrz/DiscordChatExporter/blob/master/Changelog.md)'
  on:
    branch: master
    appveyor_repo_tag: true