blank_issues_enabled: false
contact_links:
  - name: "\U0001F4D6 Read the wiki"
    url: https://github.com/Tyrrrz/DiscordChatExporter/wiki
    about: Find answers to most common questions.
  - name: "\U0001F5E8 Ask a question"
    url: https://github.com/Tyrrrz/DiscordChatExporter/discussions/new
    about: Please ask and answer questions here.