name: "\U1F5E8 Feature request"
description: Report broken functionality.
labels: [enhancement]
issue_body: false
body:
- type: markdown
  attributes:
    value: |
      - Please check existing issues (both opened and closed) to ensure that this feature hasn't been requested before.
      - Refer to the [contribution guidelines](https://github.com/Tyrrrz/DiscordChatExporter/blob/master/Contributing.md) for info on how to file a good issue.
      - If you want to ask a question instead of requesting a feature, use [**discussions**](https://github.com/Tyrrrz/DiscordChatExporter/discussions/new) instead.

- type: dropdown
  attributes:
    label: Flavor
    description: "Which flavor(s) of DiscordChatExporter does this feature request apply to?"
    multiple: true
    options:
    - GUI (Graphical User Interface)
    - CLI (Command Line Interface)

- type: textarea
  attributes:
    label: Details
    description: "Clear and thorough explanation of the feature you have in mind."
  validations:
    required: true