name: ✨ Feature request
description: Request a new feature.
labels: [enhancement]

body:
- type: markdown
  attributes:
    value: |
      🧐 **Guidelines:**

      - Search through [existing issues](https://github.com/Tyrrrz/DiscordChatExporter/issues?q=is%3Aissue) first to ensure that this feature has not been requested before.
      - Write a descriptive title for your issue. Avoid generic or vague titles such as "Some suggestions" or "Ideas for improvement".
      - Keep your issue focused on one single problem. If you have multiple feature requests, please create separate issues for each of them.
      - Provide as much context as possible in the details section. Include screenshots, screen recordings, links, references, or anything else you may consider relevant.
      - If you want to ask a question instead of requesting a feature, please use [discussions](https://github.com/Tyrrrz/DiscordChatExporter/discussions/new) instead.

- type: dropdown
  attributes:
    label: Flavor
    description: "Is this feature request related to specific flavor(s) of DiscordChatExporter? If not applicable, leave this field blank."
    multiple: true
    options:
    - GUI (Graphical User Interface)
    - CLI (Command Line Interface)

- type: dropdown
  attributes:
    label: Export format
    description: "Is this feature request related to specific export format(s)? If not applicable, leave this field blank."
    multiple: true
    options:
    - HTML
    - TXT
    - JSON
    - CSV

- type: textarea
  attributes:
    label: Details
    description: "Clear and thorough explanation of the feature you have in mind."
  validations:
    required: true