name: CD (Docker)

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Build
        run: docker build -t tyrrrz/discordchatexporter:${{ github.ref }} -t tyrrrz/discordchatexporter:stable .

      - name: Deploy
        run: |
          docker push tyrrrz/discordchatexporter:${{ github.ref }}
          docker push tyrrrz/discordchatexporter:stable